### ISSUE TITLE
File exists: error processing zips

### ISSUE THREAD

**Issue by mgigante** [chadparry/kodi-repository.chad.parry.org#5]
Hello,
I'm using create_repository.py tool to process kodi addons from a list of zip files.
Often, when running it with --datadir over sshfs mount point, I got the error shown below.
The error triggers when there are more versions of the same plugin in the zip file list.
Here is an example:

```
./create_repository.py --datadir /tmp/mnt/remote_sshfs/kodi/addons/krypton/ --compressed ./zips/*.zip
Traceback (most recent call last):
  File "/tmp/mnt/remote_sshfs/create_repository.py", line 401, in <module>
    main()
  File "/tmp/mnt/remote_sshfs/create_repository.py", line 397, in main
    args.addon, data_path, info_path, checksum_path, args.compressed)
  File "/tmp/mnt/remote_sshfs/create_repository.py", line 334, in create_repository
    raise result.exc_info[1]
OSError: [Errno 17] File exists: '/tmp/mnt/remote_sshfs/kodi/addons/krypton/script.module.requests'
```
excerpt of zips dir:
```
ls -l zips/*.zip
...
-rw-r--r-- 1 1057 1078   575645 ago  4 16:20 zips/script.module.requests-2.12.4.zip
-rw-rw-r-- 1 1057 1078   501091 lug 27 09:49 zips/script.module.requests-2.9.1.zip
...
```
Am I doing something wrong or is this an unexpected behavior?
Thanks

**Comment by mgigante** [comment]
As additional note, I saw the error to come out when --datadir is empty.
Running the same command multiple times in a row, the 'File exists' error can show up only on the first run.

**Comment by chadparry** [comment]
Oh, embarrassing, I never noticed this open ticket. So sorry!!!

This error is because of a race condition between multiple threads. For efficiency, each of those add-on sources is processed in parallel. Two threads simultaneously notice that the directory needs to be created, and then both take it upon themselves. The one that gets there last finds that the directory already exists, and it aborts the script. Worse, there's no guarantee that the `addon.xml` and other files that remain in that directory are from the most up-to-date version. The decision of which one wins is non-deterministic. Another complication is the fact that the threads don't know for sure which one might conflict with which until after examining the add-on sources, so the problem can't be solved up front when the threads are being created.

I'll create a workaround and publish it.
